import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";

const montserrat = Montserrat({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased w-full flex justify-center`}
      >
        <div className="max-w-7xl w-full lg:my-[30px] flex">
          <Sidebar />
          <div className="flex-1 bg-[#181818] rounded-3xl p-4 border border-[#333]">
          {children}
          </div>
        </div>
      </body>
    </html>
  );
}
